apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: f0a1c28dce1ae6a5e6c01787e276e040da92a466
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/squad1-front
  labels:
    app: weather-nodejs-app
    app.kubernetes.io/instance: weather-nodejs-app
    app.kubernetes.io/name: weather-nodejs-app
  name: weather-nodejs-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: weather-nodejs-app
    app.kubernetes.io/instance: weather-nodejs-app
    app.kubernetes.io/name: weather-nodejs-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: f0a1c28dce1ae6a5e6c01787e276e040da92a466
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/squad1-front
  labels:
    app: weather-nodejs-app
    app.kubernetes.io/instance: weather-nodejs-app
    app.kubernetes.io/name: weather-nodejs-app
  name: weather-nodejs-app
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: weather-nodejs-app
      app.kubernetes.io/instance: weather-nodejs-app
      app.kubernetes.io/name: weather-nodejs-app
  template:
    metadata:
      annotations:
        app.openshift.io/runtime: js
        app.openshift.io/vcs-ref: f0a1c28dce1ae6a5e6c01787e276e040da92a466
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/squad1-front
      labels:
        app: weather-nodejs-app
        app.kubernetes.io/instance: weather-nodejs-app
        app.kubernetes.io/name: weather-nodejs-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/rdemayo/weatherapp:f0a1c28dce1ae6a5e6c01787e276e040da92a466
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: weather-nodejs-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: f0a1c28dce1ae6a5e6c01787e276e040da92a466
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/squad1-front
  labels:
    app: weather-nodejs-app
    app.kubernetes.io/instance: weather-nodejs-app
    app.kubernetes.io/name: weather-nodejs-app
  name: weather-nodejs-app
spec:
  to:
    kind: Service
    name: weather-nodejs-app
    weight: 100
  wildcardPolicy: None
